version: '3'
services:
  reminder:
    networks:
      - default_network
    hostname: reminder
    container_name: reminder
    image: reminder:master
    environment:
      - HOST_HOSTNAME=${HOST_HOSTNAME}
      - MONITOR_HOST=${MONITOR_HOST}
      - MONITOR_UPDATE=${MONITOR_UPDATE}
      - MONITOR_URL=${MONITOR_URL}
      - MONITOR_SECRET=${MONITOR_SECRET}
      - MONITOR_SRC=${MONITOR_SRC}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_FROM=${MAIL_FROM}
      - MAIL_TO=${MAIL_TO}
      - HOST_URL=http://${HOST_HOSTNAME}:${PORT_CODETREATS_REMINDER_HTTP}
      - MAIL_LEVEL_OK=OFF 
      - MAIL_LEVEL_FAIL=LINK
      - TZ=Europe/Berlin
      - JOB_TITLE=Reminder
    ports:
      - ${PORT_CODETREATS_REMINDER_HTTP}:80
    volumes:
      - /media/nas/docker/data/reminder/jobs:/jobs
    restart: always
networks:
  default_network:
    name: default_network
    external: true